version: '3'

vars:
  DEBIAN_NEWEST: "TRUE"
  DEBIAN_ISO_VERSION: 12.2.0 # 11.7.0
  TARGET_CONFIG: nuc
  DEBIAN_CD_SOURCE: '{{if eq .DEBIAN_NEWEST "TRUE"}}debian-cd{{else}}cdimage/archive{{end}}'
  DEBIAN_ISO_FILENAME: debian-{{.DEBIAN_ISO_VERSION}}-amd64-netinst.iso
  DEBIAN_ISO_URL: https://cdimage.debian.org/{{.DEBIAN_CD_SOURCE}}/{{.DEBIAN_ISO_VERSION}}/amd64/iso-cd/{{.DEBIAN_ISO_FILENAME}}
  TARGET_CONFIG_FILE: configs/{{.TARGET_CONFIG}}.yml
  PRESEEDED_ISO_FILENAME: preseeded-{{.TARGET_CONFIG}}-{{.DEBIAN_ISO_FILENAME}}
  MULTIPASS_AUTH: totoro

tasks:
  ensure-pdm:
    cmd: pdm install
    desc: Ensure the pdm is initiated and a virtual environment is created
    internal: true

  generate-iso:
    cmd: pdm run main.py --iso-filename {{.DEBIAN_ISO_FILENAME}} --iso-url {{.DEBIAN_ISO_URL}} --target-config-file {{.TARGET_CONFIG_FILE}} --target-iso-filename {{.PRESEEDED_ISO_FILENAME}} --multipass-auth {{.MULTIPASS_AUTH}}
    desc: Generate a preseeded Debian ISO
    interactive: true
    sources:
      - templates/preseed.cfg.j2
      - templates/setup.sh.j2
      - "{{.TARGET_CONFIG_FILE}}"
    generates:
      - .out/{{.PRESEEDED_ISO_FILENAME}}
    requires:
      vars:
        - DEBIAN_ISO_FILENAME
        - DEBIAN_ISO_URL
        - TARGET_CONFIG_FILE
        - PRESEEDED_ISO_FILENAME
    env:
      LOG_LEVEL: DEBUG
    dir: src
    deps:
      - task: ensure-pdm
    dotenv:
      - .env

  flash-usb:
    desc: This task assumes A LOT and will be removed at some point
    deps:
      - task: generate-iso
    preconditions:
      - "[ -d src/.out ]"
    vars:
      MEDIA_DEVICE: '{{or .MEDIA_DEVICE "/dev/disk4"}}'
    requires:
      vars:
        - PRESEEDED_ISO_FILENAME
    cmds:
      - hdiutil unmount {{.MEDIA_DEVICE}}
      - sudo dd if=src/.out/{{.PRESEEDED_ISO_FILENAME}} of={{.MEDIA_DEVICE}} bs=4M status=progress
