version: '3'

env:
  DEBIAN_ISO_VERSION: 11.7.0
  DEBIAN_ISO_FILENAME: debian-{{.DEBIAN_ISO_VERSION}}-amd64-netinst.iso
  DEBIAN_ISO_URL: https://cdimage.debian.org/cdimage/archive/{{.DEBIAN_ISO_VERSION}}/amd64/iso-cd/{{.DEBIAN_ISO_FILENAME}}

tasks:
  ensure-pdm:
    desc: Ensure the pdm is initiated and a virtual environment is created
    internal: true
    cmds:
      - pdm install
      - $(pdm venv activate)

  generate-iso:
    cmd: python3 main.py
    desc: Generate a preseeded Debian ISO
    sources:
      - resources/preseed.cfg
    generates:
      - out/preseeded-{{.DEBIAN_ISO_FILENAME}}
    requires:
      vars:
        - DEBIAN_ISO_FILENAME
        - DEBIAN_ISO_URL
    env:
      LOG_LEVEL: DEBUG
    dir: src
    deps:
      - task: ensure-pdm
    dotenv:
      - .env

  flash-usb:
    desc: This task assumes A LOT and will be removed at some point
    deps:
      - task: generate-iso
    preconditions:
      - "[ -d src/out ]"
    vars:
      MEDIA_DEVICE: '{{or .MEDIA_DEVICE "/dev/disk4"}}'
    requires:
      vars:
        - DEBIAN_ISO_FILENAME
    cmds:
      - hdiutil unmount {{.MEDIA_DEVICE}}
      - sudo dd if=src/out/preseeded-{{.DEBIAN_ISO_FILENAME}} of={{.MEDIA_DEVICE}} bs=4M status=progress
