---
- name: Test /data mountpoint
  ansible.builtin.shell:
    cmd: df /data | tail -n1 |  cut -d' ' -f1
  ignore_errors: true
  register: test_res

- name: Setup storage
  when: 'test_res.stdout != "/dev/sdb1"'
  block:
    - name: Ensure tools
      ansible.builtin.apt:
        update_cache: true
        pkg: xfsprogs

    - name: Ensure data device is unmounted
      ansible.posix.mount:
        path: /dev/sdb1
        state: unmounted

    - name: Ensure data dir
      ansible.builtin.file:
        state: directory
        path: /data

    - name: Ensure data path is unmounted
      ansible.posix.mount:
        path: /data
        state: unmounted

    - name: Make filesystem on data device
      community.general.filesystem:
        dev: /dev/sdb1
        fstype: xfs
        resizefs: true
        force: true

    - name: Mount data directory under data device
      ansible.posix.mount:
        path: /data
        src: /dev/sdb1
        fstype: xfs
        state: mounted
