---
formatter: markdown table
recursive:
  enabled: true
  path: .
sections:
  show: []
output:
  file: README.md
  mode: inject
settings:
  default: true
  html: false
  anchor: false
  required: true
  type: true
  hide-empty: true
