version: '3'

tasks:
  clone-usbboot:
    cmd: git clone --depth=1 https://github.com/raspberrypi/usbboot
    desc: Clone raspberrypi/usbboot GH repository
    internal: true
    status:
      - "[ -d usbboot ]"
    silent: true

  ensure-usbboot:
    cmd: git pull
    dir: usbboot
    desc: Ensure raspberrypi/usbboot is up-to-date
    internal: true
    deps:
      - clone-usbboot

  ensure-rpiboot:
    cmd: make
    dir: usbboot
    desc: Ensure rpiboot binary is built
    internal: true
    deps:
      - ensure-usbboot
    generates:
      - usbboot/rpiboot

  rpiboot:
    cmd: ./rpiboot
    dir: usbboot
    desc: Run rpiboot
    deps:
      - ensure-rpiboot

  clean:
    cmd: rm -rf usbboot
    desc: Cleanup raspberrypi/usbboot from local path
    ignore_error: true

  reset:
    desc: Reset the cluster to a clean state
    cmds:
      - ansible-playbook reset.yml -i inventory/cluster/hosts.ini

  provision:
    desc: Provision the cluster
    cmds:
      - ansible-playbook setup.yml -i inventory/cluster/hosts.ini

  setup-kubectl:
    desc: Download kubeconfig file from the cluster to .kube and set kubectl context
    summary: |
      Download kubeconfig file from the cluster to .kube and set kubectl context
      any depending tasks should set env var KUBECONFIG=${PWD}/.kube/config
    status:
      - "[ -f .kube/config ]"
    generates:
      - .kube/config
    cmd: scp -i master.pem -r pi@master.local:~/.kube .kube
