version: '3'

includes:
  k8s:
    taskfile: k8s
    dir: k8s
    internal: true

tasks:
  kubectl:apply:
    cmds:
      - task: k8s:kubectl:apply
    desc: Deploy all applications to the Kubernetes cluster

  kubectl:delete:
    cmds:
      - task: k8s:kubectl:delete
    desc: Removy all applications from the Kubernetes cluster
