---

- name: Install btrfs-progs dependency
  ansible.builtin.apt:
    name: btrfs-progs
    force: true

- name: Ensure data device is unmounted
  ansible.posix.mount:
    path: /dev/nvme0n1
    state: unmounted

- name: Ensure data path is unmounted
  ansible.posix.mount:
    path: /var/lib/rancher/k3s
    state: unmounted

- name: Setup btrfs on data partition
  ansible.builtin.command: mkfs.btrfs -f /dev/nvme0n1

- name: Remount data directory under SSD
  ansible.posix.mount:
    path: /var/lib/rancher/k3s
    src: /dev/nvme0n1
    fstype: btrfs
    opts: "compress=zstd"
    state: mounted

- name: Try to add external drive to btrfs
  ansible.builtin.command: btrfs device add -f /dev/sda1 /var/lib/rancher/k3s
  ignore_errors: true
