apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: flood
  name: flood
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      nodePort: 30008
  selector:
    io.kompose.service: flood
  type: NodePort
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: flood
  name: flood
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flood
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: flood
    spec:
      containers:
        - image: jesec/flood:master
          name: flood
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: flood-data
      restartPolicy: Always
      volumes:
        - name: flood-data
          persistentVolumeClaim:
            claimName: flood-data
status: {}

