apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: prowlarr
  name: prowlarr
spec:
  ports:
    - name: "9696"
      port: 9696
      targetPort: 9696
      nodePort: 30006
  selector:
    io.kompose.service: prowlarr
  type: NodePort
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: prowlarr
  name: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prowlarr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: linuxserver/prowlarr
          imagePullPolicy: IfNotPresent
          env:
            - name: PGID
              value: "65534"
            - name: PUID
              value: "0"
            - name: TZ
              value: Europe/Warsaw
          ports:
            - containerPort: 9696
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: prowlarr-config
      volumes:
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: prowlarr-config
      restartPolicy: Always
status: {}
