version: '3'

tasks:
  ensure-podman:
    desc: Ensure a podman machine is present
    internal: true
    ignore_error: true
    vars:
      MACHINE_CPUS: "{{default 4 .MACHINE_CPUS}}"
      MACHINE_MEMORY: "{{default 8192 .MACHINE_MEMORY}}"
      MACHINE_NAME: "{{default default .MACHINE_NAME}}"
    cmds:
      - cmd: podman machine init --cpus {{.MACHINE_CPUS}} --memory {{.MACHINE_MEMORY}} {{.MACHINE_NAME}}
      - cmd: podman machine stop {{.MACHINE_NAME}}
      - cmd: podman machine set --rootful {{.MACHINE_NAME}}
      - cmd: podman machine start {{.MACHINE_NAME}}

  build-images:
    internal: true
    deps:
      - cmd: ensure-podman
        vars:
          MACHINE_NAME: jellyfin-builder
    cmds:
      - docker compose -f services/build.compose.yml build --pull

  push-images:
    desc: Build and push local ./services/build.compose.yml manifest
    deps:
      - build-images
    cmds:
      - task: build-images
      - docker compose -f services/build.compose.yml push

  dashboard:
    desc: Ensure the Kubernetes dashboard with a dedicated ServiceAccount are created
    cmds:
      - kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml
      - kubectl apply -f dev/ServiceAccount/sa.yml

  dashboard-token:
    desc: Copy the Bearer Token for Kubernetes dashboard to clipboard
    deps:
      - dashboard
    cmds:
      - kubectl get secret admin-user -n kubernetes-dashboard -o jsonpath={".data.token"} | base64 -d | pbcopy
      - echo 'token copied to clipboard'

  proxy:
    desc: "Start Kubernetes proxy (WARN: this is a blocking task)"
    cmds:
      - kubectl proxy

  dev:
    desc: Start a development env
    cmds:
      - task: ensure-podman
        vars:
          MACHINE_CPUS: 6
          MACHINE_MEMORY: 12288
          MACHINE_NAME: kind-cluster
      - cmd: kind create cluster --config dev/kind-config.yml
        ignore_error: true
      - task: kubectl:apply
      - task: control-plane

  control-plane:
    cmds:
      - task: dashboard-token
      - task: proxy

  clean:
    desc: Cleanup development env
    ignore_error: true
    cmds:
      - cmd: podman machine stop jellyfin-builder
      - cmd: podman machine rm jellyfin-builder <<< 'y'
      - cmd: kind delete cluster
      - cmd: podman machine stop kind-cluster
      - cmd: podman machine rm kind-cluster <<< 'y'

  kubectl-apply-build:
    desc: Build and push local docker images and deploy application
    deps:
      - push-images
    cmds:
      - task: kubectl-apply

  kubectl:apply:
    desc: Apply application
    cmds:
      - kubectl apply -f https://raw.githubusercontent.com/stakater/Reloader/master/deployments/kubernetes/reloader.yaml
      - kubectl apply --recursive -f k8s

  kubectl:delete:
    desc: Delete application
    ignore_error: true
    cmd: kubectl delete --recursive -f k8s
