version: '3'

tasks:
  ensure-podman:
    vars:
      MACHINE_CPUS: 4
      MACHINE_MEMORY: 8096
      MACHINE_NAME: ""
    cmds:
      - cmd: podman machine init --cpus {{.MACHINE_CPUS}} --memory {{.MACHINE_MEMORY}} {{.MACHINE_NAME}}
        ignore_error: true
      - cmd: podman machine stop {{.MACHINE_NAME}}
        ignore_error: true
      - cmd: podman machine set --rootful {{.MACHINE_NAME}}
        ignore_error: true
      - cmd: podman machine start {{.MACHINE_NAME}}
        ignore_error: true

  build-images:
    deps:
      - cmd: ensure-podman
        vars:
          MACHINE_NAME: jellyfin-builder
    cmds:
      - docker compose -f services/build.compose.yml build --pull

  push-images:
    deps:
      - build-images
    cmds:
      - task: build-images
      - docker compose -f services/build.compose.yml push

  dashboard:
    cmds:
      - kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml
      - kubectl apply -f dev/ServiceAccount/sa.yml

  dashboard-token:
    deps:
      - dashboard
    cmds:
      - kubectl get secret admin-user -n kubernetes-dashboard -o jsonpath={".data.token"} | base64 -d | pbcopy
      - echo 'token copied to clipboard'

  proxy:
    cmds:
      - kubectl proxy

  dev:
    cmds:
      - cmd: ensure-podman
        vars:
          MACHINE_CPUS: 6
          MACHINE_MEMORY: 12288
          MACHINE_NAME: kind-cluster
      - cmd: kind create cluster --config dev/kind-config.yml
        ignore_error: true
      - task: kubectl-apply
      - task: control-plane

  control-plane:
    cmds:
      - task: dashboard-token
      - task: proxy

  clean:
    tasks:
      - cmd: podman machine stop jellyfin-builder
        ignore_error: true
      - cmd: podman machine rm jellyfin-builder <<< 'y'
        ignore_error: true
      - cmd: kind delete cluster
        ignore_error: true
      - cmd: podman machine stop kind-cluster
        ignore_error: true
      - cmd: podman machine rm kind-cluster <<< 'y'
        ignore_error: true

  kubectl-apply-build:
    deps:
      - push-images
    cmds:
      - task: kubectl-apply

  kubectl:apply:
    desc: Apply application
    cmds:
      - kubectl apply -f https://raw.githubusercontent.com/stakater/Reloader/master/deployments/kubernetes/reloader.yaml
      - kubectl apply --recursive -f k8s

  kubectl:delete:
    desc: Delete application
    cmds:
      - cmd: kubectl delete --recursive -f k8s
        ignore_error: true
