apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: bazarr
  name: bazarr
spec:
  ports:
    - name: "webui"
      port: 6767
      targetPort: 6767
      nodePort: 30005
  selector:
    io.kompose.service: bazarr
  type: NodePort
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: bazarr
  name: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bazarr
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: bazarr
    spec:
      containers:
        - name: bazarr
          env:
            - name: PGID
              value: "65534"
            - name: PUID
              value: "0"
            - name: TZ
              value: Europe/Warsaw
          image: voxelost/bazarr:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6767
          resources:
            limits:
              cpu: 0.5
              memory: 1Gi
          volumeMounts:
            - mountPath: /config
              name: bazarr-config
            - mountPath: /home/movies
              name: radarr-movies
            - mountPath: /home/tv
              name: sonarr-tvseries
      restartPolicy: Always
      volumes:
        - name: bazarr-config
          persistentVolumeClaim:
            claimName: bazarr-config
        - name: radarr-movies
          persistentVolumeClaim:
            claimName: radarr-movies
        - name: sonarr-tvseries
          persistentVolumeClaim:
            claimName: sonarr-tvseries
status: {}
