apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: jellyseerr
  name: jellyseerr
spec:
  ports:
    - name: "5055"
      port: 5055
      targetPort: 5055
      nodePort: 30002
  selector:
    io.kompose.service: jellyseerr
  type: NodePort
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: jellyseerr
  name: jellyseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jellyseerr
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jellyseerr
    spec:
      containers:
        - name: jellyseerr
          env:
            - name: LOG_LEVEL
              value: debug
            - name: TZ
              value: Europe/Warsaw
          image: fallenbagel/jellyseerr:1.7.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5055
          resources:
            limits:
              cpu: 0.5
              memory: 1Gi
          volumeMounts:
            - mountPath: /app/config
              name: jellyseer-config
            - mountPath: /home/movies
              name: radarr-movies
            - mountPath: /home/tv
              name: sonarr-tvseries
      restartPolicy: Always
      volumes:
        - name: jellyseer-config
          persistentVolumeClaim:
            claimName: jellyseer-config
        - name: radarr-movies
          persistentVolumeClaim:
            claimName: radarr-movies
        - name: sonarr-tvseries
          persistentVolumeClaim:
            claimName: sonarr-tvseries
status: {}
