apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: jellyfin
  name: jellyfin
spec:
  ports:
    - name: "webui"
      port: 8096
      targetPort: 8096
      nodePort: 30001
  selector:
    io.kompose.service: jellyfin
  type: NodePort
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: jellyfin
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jellyfin
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:20230930.1-unstable
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8096
          resources:
            limits:
              cpu: 0.5
              memory: 1Gi
          volumeMounts:
            - mountPath: /config
              name: jellyfin-config
            - mountPath: /cache
              name: jellyfin-cache
            - mountPath: /home/movies
              name: radarr-movies
            - mountPath: /home/tv
              name: sonarr-tvseries
      restartPolicy: Always
      volumes:
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: jellyfin-cache
          persistentVolumeClaim:
            claimName: jellyfin-cache
        - name: radarr-movies
          persistentVolumeClaim:
            claimName: radarr-movies
        - name: sonarr-tvseries
          persistentVolumeClaim:
            claimName: sonarr-tvseries
status: {}

