apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: qbittorrent
  name: qbittorrent
spec:
  ports:
    - name: "webui-port"
      port: 30007
      targetPort: 30007
      nodePort: 30007
    - name: "tcp-connection-port"
      port: 6881
      targetPort: 6881
  type: NodePort
  selector:
    io.kompose.service: qbittorrent
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: qbittorrent
  name: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: qbittorrent
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: linuxserver/qbittorrent:4.5.5
          imagePullPolicy: IfNotPresent
          resources: {}
          volumeMounts:
            - mountPath: /downloads
              name: qbittorrent-downloads
          ports:
            - containerPort: 30007
            - containerPort: 6881
          env:
            - name: WEBUI_PORT
              value: "30007"
      restartPolicy: Always
      volumes:
        - name: qbittorrent-downloads
          persistentVolumeClaim:
            claimName: qbittorrent-downloads
status: {}
