apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: radarr
  name: radarr
spec:
  ports:
    - name: "7878"
      port: 7878
      targetPort: 7878
      nodePort: 30003
  selector:
    io.kompose.service: radarr
  type: NodePort
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: radarr
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: radarr
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: radarr
    spec:
      containers:
        - name: radarr
          env:
            - name: PGID
              value: "65534"
            - name: PUID
              value: "0"
            - name: TZ
              value: Europe/Warsaw
          image: voxelost/radarr:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7878
          resources:
            limits:
              cpu: 0.5
              memory: 1Gi
          volumeMounts:
            - mountPath: /home/movies
              name: radarr-movies
            - mountPath: /config
              name: radarr-config
            - mountPath: /downloads
              name: qbittorrent-downloads
      restartPolicy: Always
      volumes:
        - name: radarr-movies
          persistentVolumeClaim:
            claimName: radarr-movies
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: qbittorrent-downloads
          persistentVolumeClaim:
            claimName: qbittorrent-downloads
status: {}
