apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: sonarr
  name: sonarr
spec:
  ports:
    - name: "8989"
      port: 8989
      targetPort: 8989
      nodePort: 30004
  selector:
    io.kompose.service: sonarr
  type: NodePort
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: sonarr
  name: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sonarr
    spec:
      containers:
        - name: sonarr
          env:
            - name: PGID
              value: "65534"
            - name: PUID
              value: "0"
            - name: TZ
              value: Europe/Warsaw
          image: voxelost/sonarr:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8989
          resources:
            limits:
              cpu: 0.5
              memory: 1Gi
          volumeMounts:
            - mountPath: /config
              name: sonarr-config
            - mountPath: /home/tv
              name: sonarr-tvseries
            - mountPath: /downloads
              name: qbittorrent-downloads
      restartPolicy: Always
      volumes:
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: sonarr-tvseries
          persistentVolumeClaim:
            claimName: sonarr-tvseries
        - name: qbittorrent-downloads
          persistentVolumeClaim:
            claimName: qbittorrent-downloads
status: {}
