---

- name: Install btrfs-progs dependency
  ansible.builtin.apt:
    name: btrfs-progs
    force: true

- name: Ensure data dir
  ansible.builtin.file:
    path: /var/lib/rancher/k3s
    state: directory

- name: Ensure data dir is unmounted
  ansible.posix.mount:
    path: /var/lib/rancher/k3s
    state: unmounted

# - name: Copy eMMC to data device
#   ansible.builtin.command: dd if=/dev/mmcblk0 of=/dev/nvme0n1 bs=4MB

- name: Ensure boot dir is unmounted
  ansible.posix.mount:
    path: /boot
    state: unmounted

- name: Remount boot directory under SSD
  ansible.posix.mount:
    path: /boot
    src: /dev/nvme0n1p1
    state: mounted
    fstype: vfat

- name: Setup btrfs on the data partition
  community.general.filesystem:
    dev: /dev/nvme0n1p2
    fstype: btrfs
    resizefs: true
    force: true

- name: Remount data directory under SSD
  ansible.posix.mount:
    path: /var/lib/rancher/k3s
    src: /dev/nvme0n1p2
    fstype: btrfs
    opts: "compress=zstd"
    state: mounted

