apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-ddns
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cloudflare-ddns
            image: voxelost/cloudflare-ddns:v0.1.9
            imagePullPolicy: IfNotPresent
            envFrom:
            - secretRef:
                name: ddns-secret
          restartPolicy: OnFailure

  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  schedule: "*/20 * * * *"
