version: '3'

tasks:
  reset:
    desc: Reset the cluster to a clean state
    cmds:
      - ansible-playbook reset.yml -i inventory/cluster/hosts.ini

  provision:
    desc: Provision the cluster
    cmds:
      - ansible-playbook setup.yml -i inventory/cluster/hosts.ini

  setup-kubectl:
    desc: Download kubeconfig file from the cluster to .kube and set kubectl context
    generates:
      - .kube/config
    cmds:
      - cmd: rm -rf .kube
        ignore_error: true
      - scp -i master.pem -r pi@master.local:~/.kube .kube
      - cmd: echo "You need to export the new kubeconfig file now:"
        silent: true
      - cmd: echo "export KUBECONFIG=${PWD}/.kube/config"
        silent: true
