version: '3.8'

services:
  bazarr:
    build:
      dockerfile: bazarr.dockerfile
    image: voxelost/bazarr:v1
    environment:
    - 'PUID=0'
    - 'PGID=65534'
    - 'TZ=Europe/Warsaw'

  radarr:
    build:
      dockerfile: radarr.dockerfile
    image: voxelost/radarr:v1
    environment:
    - 'PUID=0'
    - 'PGID=65534'
    - 'TZ=Europe/Warsaw'

  sonarr:
    build:
      dockerfile: sonarr.dockerfile

    image: voxelost/sonarr:v1
    environment:
    - 'PUID=0'
    - 'PGID=65534'
    - 'TZ=Europe/Warsaw'

  # rtorrent:
  #   build:
  #     dockerfile: rtorrent.dockerfile

  #   image: voxelost/rtorrent:v1

  jellyfin-exporter:
    build:
      dockerfile: jellyfin-exporter.dockerfile
    image: voxelost/jellyfin-exporter:v2
