---
hostname: hostname
root_password: root_passwd
user:
  name: user
  password: user_passwd
public_key: ""
additional_packages: []
script:
  preseed:
    location: /root/preseed-setup.sh
    additional_steps: []
  firstboot:
    location: /root/firstboot-setup.sh
    additional_steps: []
